title:               Wade in the Water

# Versioning
current_version: 1.5.0
foundation_version: 6.0.0

author:
  name:             Maya Pascal
  email:            mayamere21@gmail.com
  twitter:          meetyourm

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./
destination:        ./static

port:               9002
baseurl:
url:                http://wadezine.com

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          "Wade in the Water"
site_description:  "The goal of Wade in the Water is to compose an image of the impact of the movement for Black lives has since the unrest in Ferguson in the summer and fall of 2014, from snapshots provided by a range of Black interviewees."
site_copyright:     "Copyright (c) 2016 Maya Pascal"
site_url:           "http://wadezine.com/"
site_email:         "yatriksolanki@gmail.com"
site_phone:

collections:
  interviews:
    output: true
    permalink: /interviews/:title.html

defaults:
  - scope:
      path: ""
      type: interviews
    values:
      layout: interview
      base_url: ""

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          assets/stylesheets/
  style:            :compressed

# Configuration for Prose.io
# prose:
#   rooturl: '/'
# #   siteurl: 'http://prose.github.io/starter/'
# #   relativeLinks: 'http://prose.github.io/starter/links.jsonp'
#   media: 'assets'
#   ignore:
#     - _layouts
#   metadata:
#     source/_posts:
#       - name: "layout"
#         field:
#           element: "hidden"
#           value: "blog"
#       - name: "topics"
#         field:
#           element: "multiselect"
#           label: "Add Tags"
#           placeholder: "Choose Tags"
#           # options:
#           #   - name: "Apples"
#           #     value: "apples"
#           #   - name: "Bananas"
#           #     value: "bananas"
#     static:
#       - name: "layout"
#         field:
#           element: "hidden"
#           value: "page"
#       - name: "permalink"
#         field:
#           element: "text"
#           label: "Permalink"
#           value: ""
